### ISSUE TITLE
Question: why not use $parse for label templates?

### ISSUE THREAD

**Issue by ashmind** [kgiszewski/Archetype#381]
Not really a bug, but something I was curious about -- why not use Angular's `$parse` instead of regexes in archetypeLabelService?

**Comment by kgiszewski** [comment]
That is a good question. Most likely when I implemented them a few years back I didn't know about it. If there is a better way, I'd love a PR 😉


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Andrey Shchekin <notifications@github.com> Date: 11/27/16  4:13 PM  (GMT-05:00) To: kgiszewski/Archetype <Archetype@noreply.github.com> Subject: [kgiszewski/Archetype] Question: why not use $parse for label templates? (#381) 
Not really a bug, but something I was curious about -- why not use Angular's $parse instead of regexes in archetypeLabelService?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kgiszewski/Archetype","title":"kgiszewski/Archetype","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kgiszewski/Archetype"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Question: why not use $parse for label templates? (#381)"}],"action":{"name":"View Issue","url":"https://github.com/kgiszewski/Archetype/issues/381"}}}

**Comment by ashmind** [comment]
@kgiszewski Thanks -- I'll take a look if I have time.

**Comment by kgiszewski** [comment]
Don't feel compelled to do one. If it's broke, then we can worry about it ☺


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Andrey Shchekin <notifications@github.com> Date: 11/27/16  5:29 PM  (GMT-05:00) To: kgiszewski/Archetype <Archetype@noreply.github.com> Cc: Kevin Giszewski <me@giszewski.com>, Mention <mention@noreply.github.com> Subject: Re: [kgiszewski/Archetype] Question: why not use $parse for label templates? (#381) 
@kgiszewski Thanks -- I'll take a look if I have time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kgiszewski/Archetype","title":"kgiszewski/Archetype","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kgiszewski/Archetype"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ashmind in #381: @kgiszewski Thanks -- I'll take a look if I have time."}],"action":{"name":"View Issue","url":"https://github.com/kgiszewski/Archetype/issues/381#issuecomment-263152460"}}}

**Comment by kjac** [comment]
@ashmind I'm going to close this now... but do feel free to push a PR if you have a better solution for label templates 😄
